# ============================================================================
# CloudDesk Self-Hosted Setup Script (Windows PowerShell)
# Generates secure secrets and creates .env configuration
# ============================================================================

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "╔═══════════════════════════════════════════════════════════╗" -ForegroundColor Blue
Write-Host "║           CloudDesk Self-Hosted Setup Script              ║" -ForegroundColor Blue
Write-Host "╚═══════════════════════════════════════════════════════════╝" -ForegroundColor Blue
Write-Host ""

# Check for Node.js
try {
    $nodeVersion = node --version
    Write-Host "✓ Node.js found: $nodeVersion" -ForegroundColor Green
} catch {
    Write-Host "Error: Node.js is required but not installed." -ForegroundColor Red
    Write-Host "Please install Node.js 18+ from https://nodejs.org"
    exit 1
}

# Check for Docker
try {
    $dockerVersion = docker --version
    Write-Host "✓ Docker found: $dockerVersion" -ForegroundColor Green
} catch {
    Write-Host "Warning: Docker is not installed." -ForegroundColor Yellow
    Write-Host "Docker is required to run CloudDesk. Install from https://docker.com"
}

Write-Host ""
Write-Host "Generating secure secrets..." -ForegroundColor Green

# Generate secrets using Node.js
function Generate-Secret {
    return (node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
}

function Generate-Password {
    return (node -e "console.log(require('crypto').randomBytes(16).toString('base64').replace(/[^a-zA-Z0-9]/g, '').slice(0, 24))")
}

$JWT_ACCESS_SECRET = Generate-Secret
$JWT_REFRESH_SECRET = Generate-Secret
$ENCRYPTION_KEY = Generate-Secret
$MONGO_ROOT_PASSWORD = Generate-Password
$MONGO_PASSWORD = Generate-Password
$ADMIN_SECRET = Generate-Password

Write-Host "✓ Secrets generated" -ForegroundColor Green
Write-Host ""

# Get configuration from user
Write-Host "Please provide the following configuration:" -ForegroundColor Blue
Write-Host ""

$DOMAIN = Read-Host "Domain name (e.g., clouddesk.yourcompany.com) [localhost]"
if ([string]::IsNullOrWhiteSpace($DOMAIN)) { $DOMAIN = "localhost" }

$ACME_EMAIL = Read-Host "SSL email for Let's Encrypt (e.g., admin@yourcompany.com) [admin@example.com]"
if ([string]::IsNullOrWhiteSpace($ACME_EMAIL)) { $ACME_EMAIL = "admin@example.com" }

$APP_NAME = Read-Host "Application name [CloudDesk]"
if ([string]::IsNullOrWhiteSpace($APP_NAME)) { $APP_NAME = "CloudDesk" }

$LICENSE_KEY = Read-Host "License key (leave blank for Community edition)"

Write-Host ""
Write-Host "Creating .env file..." -ForegroundColor Green

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$envContent = @"
# ============================================================================
# CloudDesk Self-Hosted Configuration
# Generated by setup script on $timestamp
# ============================================================================

# Domain Configuration
DOMAIN=$DOMAIN
ACME_EMAIL=$ACME_EMAIL

# Application
APP_NAME=$APP_NAME
APP_URL=https://$DOMAIN
NODE_ENV=production
PORT=3000

# Database - MongoDB
MONGO_ROOT_USERNAME=admin
MONGO_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
MONGO_USERNAME=clouddesk
MONGO_PASSWORD=$MONGO_PASSWORD
MONGODB_URI=mongodb://clouddesk:$($MONGO_PASSWORD)@mongodb:27017/clouddesk?authSource=clouddesk

# Redis
REDIS_URL=redis://redis:6379

# Security Secrets (auto-generated - keep these safe!)
JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
ENCRYPTION_KEY=$ENCRYPTION_KEY
ADMIN_SECRET=$ADMIN_SECRET

# Token Configuration
JWT_ACCESS_EXPIRY=24h
JWT_REFRESH_EXPIRY=7d

# Session Configuration
SESSION_TIMEOUT_MINUTES=30
MAX_SESSIONS_PER_USER=5

# Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100
AUTH_RATE_LIMIT_MAX=60
API_RATE_LIMIT_MAX=300

# CORS
CORS_ORIGINS=https://$DOMAIN

# Logging
LOG_LEVEL=info

# License
LICENSE_KEY=$LICENSE_KEY

# Docker
DOCKER_NETWORK=clouddesk-network
WORKER_IMAGE=clouddesk/session-worker:latest
"@

$envContent | Out-File -FilePath ".env" -Encoding UTF8
Write-Host "✓ .env file created" -ForegroundColor Green
Write-Host ""

# Create backup of secrets
$secretsFile = "secrets-$(Get-Date -Format 'yyyyMMdd-HHmmss').txt"
$secretsContent = @"
CloudDesk Secrets Backup
Generated: $timestamp
Domain: $DOMAIN

IMPORTANT: Store this file securely and delete after backing up!

MongoDB Root Password: $MONGO_ROOT_PASSWORD
MongoDB App Password: $MONGO_PASSWORD
JWT Access Secret: $JWT_ACCESS_SECRET
JWT Refresh Secret: $JWT_REFRESH_SECRET
Encryption Key: $ENCRYPTION_KEY
Admin Secret: $ADMIN_SECRET
"@

$secretsContent | Out-File -FilePath $secretsFile -Encoding UTF8
Write-Host "Secrets backup saved to: $secretsFile" -ForegroundColor Yellow
Write-Host "Please store this file securely and delete it after backing up!" -ForegroundColor Yellow
Write-Host ""

Write-Host "╔═══════════════════════════════════════════════════════════╗" -ForegroundColor Blue
Write-Host "║                    Setup Complete!                        ║" -ForegroundColor Blue
Write-Host "╚═══════════════════════════════════════════════════════════╝" -ForegroundColor Blue
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Green
Write-Host ""
Write-Host "1. Review and customize .env if needed"
Write-Host ""
Write-Host "2. Start CloudDesk:" -ForegroundColor White
Write-Host "   docker compose -f docker-compose.selfhosted.yml up -d" -ForegroundColor Yellow
Write-Host ""
Write-Host "3. Check status:" -ForegroundColor White
Write-Host "   docker compose -f docker-compose.selfhosted.yml ps" -ForegroundColor Yellow
Write-Host ""
Write-Host "4. View logs:" -ForegroundColor White
Write-Host "   docker compose -f docker-compose.selfhosted.yml logs -f" -ForegroundColor Yellow
Write-Host ""
Write-Host "5. Access CloudDesk at:" -ForegroundColor White
Write-Host "   https://$DOMAIN" -ForegroundColor Green
Write-Host ""
Write-Host "6. Admin dashboard:" -ForegroundColor White
Write-Host "   https://$DOMAIN/admin" -ForegroundColor Green
Write-Host ""
Write-Host "Remember to backup your $secretsFile and then delete it!" -ForegroundColor Yellow
