#!/bin/bash
# ============================================================================
# CloudDesk Self-Hosted Setup Script
# Generates secure secrets and creates .env configuration
# ============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║           CloudDesk Self-Hosted Setup Script              ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check for Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is required but not installed.${NC}"
    echo "Please install Node.js 18+ from https://nodejs.org"
    exit 1
fi

# Check for Docker
if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}Warning: Docker is not installed.${NC}"
    echo "Docker is required to run CloudDesk. Install from https://docker.com"
fi

# Generate secure secrets using Node.js crypto
generate_secret() {
    node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
}

generate_password() {
    node -e "console.log(require('crypto').randomBytes(16).toString('base64').replace(/[^a-zA-Z0-9]/g, '').slice(0, 24))"
}

echo -e "${GREEN}Generating secure secrets...${NC}"

JWT_ACCESS_SECRET=$(generate_secret)
JWT_REFRESH_SECRET=$(generate_secret)
ENCRYPTION_KEY=$(generate_secret)
MONGO_ROOT_PASSWORD=$(generate_password)
MONGO_PASSWORD=$(generate_password)
ADMIN_SECRET=$(generate_password)

echo -e "${GREEN}✓ Secrets generated${NC}"
echo ""

# Get configuration from user
echo -e "${BLUE}Please provide the following configuration:${NC}"
echo ""

read -p "Domain name (e.g., clouddesk.yourcompany.com): " DOMAIN
DOMAIN=${DOMAIN:-localhost}

read -p "SSL email for Let's Encrypt (e.g., admin@yourcompany.com): " ACME_EMAIL
ACME_EMAIL=${ACME_EMAIL:-admin@example.com}

read -p "Application name [CloudDesk]: " APP_NAME
APP_NAME=${APP_NAME:-CloudDesk}

read -p "License key (leave blank for Community edition): " LICENSE_KEY
LICENSE_KEY=${LICENSE_KEY:-}

echo ""
echo -e "${GREEN}Creating .env file...${NC}"

# Create .env file
cat > .env << EOF
# ============================================================================
# CloudDesk Self-Hosted Configuration
# Generated by setup script on $(date)
# ============================================================================

# Domain Configuration
DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}

# Application
APP_NAME=${APP_NAME}
APP_URL=https://${DOMAIN}
NODE_ENV=production
PORT=3000

# Database - MongoDB
MONGO_ROOT_USERNAME=admin
MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
MONGO_USERNAME=clouddesk
MONGO_PASSWORD=${MONGO_PASSWORD}
MONGODB_URI=mongodb://clouddesk:${MONGO_PASSWORD}@mongodb:27017/clouddesk?authSource=clouddesk

# Redis
REDIS_URL=redis://redis:6379

# Security Secrets (auto-generated - keep these safe!)
JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
ADMIN_SECRET=${ADMIN_SECRET}

# Token Configuration
JWT_ACCESS_EXPIRY=24h
JWT_REFRESH_EXPIRY=7d

# Session Configuration
SESSION_TIMEOUT_MINUTES=30
MAX_SESSIONS_PER_USER=5

# Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100
AUTH_RATE_LIMIT_MAX=60
API_RATE_LIMIT_MAX=300

# CORS
CORS_ORIGINS=https://${DOMAIN}

# Logging
LOG_LEVEL=info

# License
LICENSE_KEY=${LICENSE_KEY}

# Docker
DOCKER_NETWORK=clouddesk-network
WORKER_IMAGE=clouddesk/session-worker:latest
EOF

echo -e "${GREEN}✓ .env file created${NC}"
echo ""

# Create backup of secrets
SECRETS_FILE="secrets-$(date +%Y%m%d-%H%M%S).txt"
cat > ${SECRETS_FILE} << EOF
CloudDesk Secrets Backup
Generated: $(date)
Domain: ${DOMAIN}

IMPORTANT: Store this file securely and delete after backing up!

MongoDB Root Password: ${MONGO_ROOT_PASSWORD}
MongoDB App Password: ${MONGO_PASSWORD}
JWT Access Secret: ${JWT_ACCESS_SECRET}
JWT Refresh Secret: ${JWT_REFRESH_SECRET}
Encryption Key: ${ENCRYPTION_KEY}
Admin Secret: ${ADMIN_SECRET}
EOF

chmod 600 ${SECRETS_FILE}
echo -e "${YELLOW}Secrets backup saved to: ${SECRETS_FILE}${NC}"
echo -e "${YELLOW}Please store this file securely and delete it after backing up!${NC}"
echo ""

echo -e "${BLUE}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║                    Setup Complete!                        ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}Next steps:${NC}"
echo ""
echo "1. Review and customize .env if needed"
echo ""
echo "2. Start CloudDesk:"
echo "   ${YELLOW}docker compose -f docker-compose.selfhosted.yml up -d${NC}"
echo ""
echo "3. Check status:"
echo "   ${YELLOW}docker compose -f docker-compose.selfhosted.yml ps${NC}"
echo ""
echo "4. View logs:"
echo "   ${YELLOW}docker compose -f docker-compose.selfhosted.yml logs -f${NC}"
echo ""
echo "5. Access CloudDesk at:"
echo "   ${GREEN}https://${DOMAIN}${NC}"
echo ""
echo "6. Admin dashboard:"
echo "   ${GREEN}https://${DOMAIN}/admin${NC}"
echo ""
echo -e "${YELLOW}Remember to backup your ${SECRETS_FILE} and then delete it!${NC}"
